name = input('Введите назавние обучающего университета ')
print(len(name))
print(name.upper())
print(name.upper())
print(name.lower())
print(name.replace(' ' , ''))
print(name[0])
print(name[-1])